# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 713c1665158029e9693772cd17c5cd9b24f6c01cf995f5995276e18dc20b6b5e6f5295b5f88b051721d410d120e8ea63807507263b019c0081d2a3bd87ae5029

test:
  secret_key_base: 2a5fbb7a752b319dffaca3bfcf13a886d7e7a9470f6e5767b048e3057c7fb86761415950cf263649e40ea782cbba10c54274b72313d5d4700957d64abeae1f31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
